Update RISC-V infrastructure. Note that this version does not run in QEMU or Spike at the moment, since the block device support has not been ported to the priv-1.9 version yet.

diff --git a/scripts/runqemu-internal b/scripts/runqemu-internal
--- a/scripts/runqemu-internal
+++ b/scripts/runqemu-internal
@@ -528,6 +528,12 @@ config_qemumicroblaze() {
 }
 
 config_qemuriscv64() {
+    echo
+    echo "ERROR: QEMU cannot run riscv-poky images at the moment, due to a missing block"
+    echo "device driver. Please contact maas@eecs.berkeley.edu if you are interested in"
+    echo "helping us restore the block device driver support."
+    echo
+    exit 1
     set_mem_size 128
     BBL_PATH="$OECORE_NATIVE_SYSROOT/usr/share/riscv-pk/bbl"
     QEMU=qemu-system-riscv
diff --git a/scripts/runspike b/scripts/runspike
--- a/scripts/runspike
+++ b/scripts/runspike
@@ -110,6 +110,13 @@ while true; do
     arg=${1}
     case "$arg" in
         "riscv64")
+            echo
+            echo "ERROR: Spike cannot run riscv-poky images at the moment, due to a missing block"
+            echo "device driver. Please contact maas@eecs.berkeley.edu if you are interested in"
+            echo "helping us restore the block device driver support."
+            echo
+            exit 1
+
             [ -z "$MACHINE" ] && MACHINE=$arg || \
                 error "conflicting MACHINE types [$MACHINE] and [$arg]"
             ;;
